### PR TITLE
Upgrade to fp-bindgen v3.0.0

### PR DESCRIPTION
**Pull request by arendjr**
# Description

Upgrades to fp-bindgen v3.0.0: https://github.com/fiberplane/fp-bindgen/pull/193

See also: https://github.com/fiberplane/fiberplane/pull/52

# Checklist

- [ ] Update CHANGELOG.md

### CODE REVIEW

**Review by mellowagain — APPROVED** [review]
ci is failing but else ok 👍

**Comment by arendjr** [comment]
To be honest I don't quite understand what is going wrong with the CI here... `cargo clippy` works fine locally, the CI complains about something that seems related to `clap`, though I didn't touch that dependency either, and the error messages are not very clear in the context they're given... :shrug:

**Comment by gagbo** [comment]
Yeah that's weird, maybe the CI here is using an outdated version of something in the rust toolchain? Or maybe a version of something related to the locked Clap got yanked ? Updating clap in the lockfile might help?

**Comment by arendjr** [comment]
I can give that a try :)

**Pull request merged**
